name: Add Accepted Issues to Project

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'accepted'
    
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/AndyLevesque/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: accepted
          label-operator: OR

      - name: Comment on issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This issue has been accepted and added to the QuackWorks OpenSCAD Development project!'
            })
